# Generated by Django 5.0.6 on 2024-07-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='name',
        ),
    ]
