# Generated by Django 5.0.6 on 2024-07-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0005_remove_notification_name_notification_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
